gui:
  title: '%crate_name% Crate!'
  size: 54
  reward_slots:
    - '12'
    - '13'
    - '14'
    - '21'
    - '22'
    - '23'
    - '30'
    - '31'
    - '32'
    - '40*'
  default_reward_item: CHEST name:Default_Reward_#%number% lore:|Click_to_open|_
  op_reward_item: ENDER_CHEST name:OP_Reward_#%number% lore:|Click_to_open|_

